services:
  api:
    build: .

    env_file:
      - ./.env

    ports:
      - 8000:8000
  
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - mynetwork

  postgres:
    image: postgres

    env_file:
      - ./.env.postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

    volumes:
      - postgres-db:/var/lib/postgresql/data

    networks:
      - mynetwork

volumes:
  postgres-db:

networks:
  mynetwork:
    driver: bridge
